name: basic_phx_app
on_project_first_start: docker compose up -d  && mix setup
windows:
  - editor:
      layout: 49d3,364x88,0,0{280x88,0,0,20,83x88,281,0,22}
      panes:
        - vim
        - mix test.interactive --stale
  - server: 
      layout: even-vertical
      panes:
        - docker compose up
        - mix phx.server
